- name: Add Disney Github to hosts
  lineinfile:
    dest: /etc/hosts
    state: present
    line: '35.162.20.56    github.disney.com'

- name: Add Disney Nexus to hosts
  lineinfile:
    dest: /etc/hosts
    state: present
    line: '52.39.140.232   nexus.disney.com'

- name: Add Disney Gitlab to hosts
  lineinfile:
    dest: /etc/hosts
    state: present
    line: '54.244.186.224  gitlab.disney.com'

- name: Add DTCI Nexus non-prod to hosts
  lineinfile:
    dest: /etc/hosts
    state: present
    line: '34.193.176.67 nexus-test.nonprod.cd.dtci.co'

- name: Add DTCI Nexus to hosts
  lineinfile:
    dest: /etc/hosts
    state: present
    line: '#54.165.99.134 nexus.dtci.co'
  
- name: Add Sonarqube non-prod to hosts
  lineinfile:
    dest: /etc/hosts
    state: present
    line: '52.5.94.52 sonarqube-ee.nonprod.cd.dtci.co'

- name: Add Sonarqube to hosts
  lineinfile:
    dest: /etc/hosts
    state: present
    line: '#34.196.237.89 sonarqube-ee.cd.dtci.co'
